name: CI Test for test_kvstore.py

# This will trigger the workflow on every push or pull request to the repository
on:
  push:
    branches:
      - main  # Or the branch you want
  pull_request:
    branches:
      - main  # Or the branch you want

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository to the runner
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python (e.g., Python 3.10)
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # Set your Python version

      # Install dependencies (e.g., pytest and any other requirements)
      - name: Install dependencies
        run: |
          pip install pytest
          pip install -r requirements.txt  # If you have a requirements file

      # Run your tests
      - name: Run tests
        run: |
          pytest test_kvstore.py